name: Deploy docs to github pages

on:
  push:
    branches:
    - dev
    - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --force trunk

    - name: Add WASM build target
      run: |
        rustup target add wasm32-unknown-unknown

    - name: Build docs
      working-directory: ./coral-docs
      run: |
        trunk build
      env:
        TRUNK_BUILD_PUBLIC_URL: ./

    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/dev' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coral-docs/dist
